#pragma once

#include <Features/Combat/SniperRifles/NoScopeInaccuracyVis/NoScopeInaccuracyVisConfigVariables.h>
#include <Features/Combat/Aimbot/AimbotConfigVariables.h>
#include <Features/Combat/NoRecoil/NoRecoilConfigVariables.h>
#include <Features/Combat/NoSpread/NoSpreadConfigVariables.h>
#include <Features/Combat/Triggerbot/TriggerbotConfigVariables.h>
#include <Features/Misc/BunnyHop/BunnyHopConfigVariables.h>
#include <Features/Misc/AutoStrafe/AutoStrafeConfigVariables.h>
#include <Features/Misc/ThirdPerson/ThirdPersonConfigVariables.h>
#include <Features/Inventory/InventoryChanger/InventoryChangerConfigVariables.h>
#include <Features/Hud/BombPlantAlert/BombPlantAlertConfigVariables.h>
#include <Features/Hud/BombTimer/BombTimerConfigVariables.h>
#include <Features/Hud/DefusingAlert/DefusingAlertConfigVariables.h>
#include <Features/Hud/KillfeedPreserver/KillfeedPreserverConfigVariables.h>
#include <Features/Hud/PostRoundTimer/PostRoundTimerConfigVariables.h>
#include <Features/Sound/SoundVisualizationConfigVariables.h>
#include <Features/Visuals/ModelGlow/ModelGlowConfigVariables.h>
#include <Features/Visuals/OutlineGlow/OutlineGlowConfigVariables.h>
#include <Features/Visuals/PlayerEsp/PlayerEspConfigVariables.h>
#include <Features/Visuals/PlayerInfoInWorld/PlayerInfoInWorldConfigVariables.h>
#include <Features/Visuals/ViewmodelMod/ViewmodelModConfigVariables.h>
#include <Features/Visuals/GrenadePrediction/GrenadePredictionConfigVariables.h>
#include <Utils/TypeList.h>

using ConfigVariableTypes = TypeList<
    BombTimerEnabled,
    DefusingAlertEnabled,
    KillfeedPreserverEnabled,
    PostRoundTimerEnabled,
    BombBeepSoundVisualizationEnabled,
    BombDefuseSoundVisualizationEnabled,
    BombPlantSoundVisualizationEnabled,
    FootstepSoundVisualizationEnabled,
    WeaponReloadSoundVisualizationEnabled,
    WeaponScopeSoundVisualizationEnabled,
    model_glow_vars::Enabled,
    model_glow_vars::GlowPlayers,
    model_glow_vars::PlayerGlowColorMode,
    model_glow_vars::GlowOnlyEnemies,
    model_glow_vars::GlowWeapons,
    model_glow_vars::GlowDroppedBomb,
    model_glow_vars::GlowTickingBomb,
    model_glow_vars::GlowDefuseKits,
    model_glow_vars::GlowGrenadeProjectiles,
    model_glow_vars::PlayerBlueHue,
    model_glow_vars::PlayerGreenHue,
    model_glow_vars::PlayerYellowHue,
    model_glow_vars::PlayerOrangeHue,
    model_glow_vars::PlayerPurpleHue,
    model_glow_vars::TeamTHue,
    model_glow_vars::TeamCTHue,
    model_glow_vars::LowHealthHue,
    model_glow_vars::HighHealthHue,
    model_glow_vars::AllyHue,
    model_glow_vars::EnemyHue,
    model_glow_vars::MolotovHue,
    model_glow_vars::FlashbangHue,
    model_glow_vars::HEGrenadeHue,
    model_glow_vars::SmokeGrenadeHue,
    model_glow_vars::DroppedBombHue,
    model_glow_vars::TickingBombHue,
    model_glow_vars::DefuseKitHue,
    player_esp_vars::Enabled,
    player_esp_vars::OnlyEnemies,
    player_esp_vars::ShowBox,
    player_esp_vars::ShowSkeleton,
    player_esp_vars::ShowHeadDot,
    player_esp_vars::ShowHealthBar,
    player_esp_vars::VisibilityCheck,
    player_esp_vars::BoxType,
    outline_glow_vars::Enabled,
    outline_glow_vars::GlowDefuseKits,
    outline_glow_vars::GlowDroppedBomb,
    outline_glow_vars::GlowGrenadeProjectiles,
    outline_glow_vars::GlowHostages,
    outline_glow_vars::GlowPlayers,
    outline_glow_vars::GlowOnlyEnemies,
    outline_glow_vars::PlayerGlowColorMode,
    outline_glow_vars::GlowTickingBomb,
    outline_glow_vars::GlowWeapons,
    outline_glow_vars::PlayerBlueHue,
    outline_glow_vars::PlayerGreenHue,
    outline_glow_vars::PlayerYellowHue,
    outline_glow_vars::PlayerOrangeHue,
    outline_glow_vars::PlayerPurpleHue,
    outline_glow_vars::TeamTHue,
    outline_glow_vars::TeamCTHue,
    outline_glow_vars::LowHealthHue,
    outline_glow_vars::HighHealthHue,
    outline_glow_vars::AllyHue,
    outline_glow_vars::EnemyHue,
    outline_glow_vars::MolotovHue,
    outline_glow_vars::FlashbangHue,
    outline_glow_vars::HEGrenadeHue,
    outline_glow_vars::SmokeGrenadeHue,
    outline_glow_vars::DroppedBombHue,
    outline_glow_vars::TickingBombHue,
    outline_glow_vars::DefuseKitHue,
    outline_glow_vars::HostageHue,
    player_info_vars::Enabled,
    player_info_vars::OnlyEnemies,
    player_info_vars::PlayerPositionArrowEnabled,
    player_info_vars::PlayerPositionArrowColorMode,
    player_info_vars::PlayerNameEnabled,
    player_info_vars::PlayerNameColorMode,
    player_info_vars::PlayerHealthEnabled,
    player_info_vars::PlayerHealthColorMode,
    player_info_vars::ActiveWeaponIconEnabled,
    player_info_vars::ActiveWeaponAmmoEnabled,
    player_info_vars::BombCarrierIconEnabled,
    player_info_vars::BombPlantIconEnabled,
    player_info_vars::BombDefuseIconEnabled,
    player_info_vars::HostagePickupIconEnabled,
    player_info_vars::HostageRescueIconEnabled,
    player_info_vars::BlindedIconEnabled,
    viewmodel_mod_vars::Enabled,
    viewmodel_mod_vars::ModifyFov,
    viewmodel_mod_vars::Fov,
    no_scope_inaccuracy_vis_vars::Enabled,
    aimbot_vars::Enabled,
    aimbot_vars::TeamCheck,
    aimbot_vars::VisibilityCheck,
    aimbot_vars::RecoilControl,
    aimbot_vars::OnlyWhenScoped,
    aimbot_vars::DisableWhenFlashed,
    aimbot_vars::RequireHoldKey,
    aimbot_vars::DrawFov,
    aimbot_vars::Fov,
    aimbot_vars::Smoothness,
    aimbot_vars::Hitbox,
    no_recoil_vars::Enabled,
    no_recoil_vars::Strength,
    no_spread_vars::Enabled,
    triggerbot_vars::Enabled,
    triggerbot_vars::TeamCheck,
    triggerbot_vars::OnlyWhenScoped,
    triggerbot_vars::DisableWhenFlashed,
    triggerbot_vars::DelayMs,
    bunnyhop_vars::Enabled,
    autostrafe_vars::Enabled,
    thirdperson_vars::Enabled,
    thirdperson_vars::Distance,
    inventory_changer_vars::Enabled,
    inventory_changer_vars::AkSkin,
    inventory_changer_vars::M4Skin,
    inventory_changer_vars::AwpSkin,
    inventory_changer_vars::DeagleSkin,
    inventory_changer_vars::KnifeSkin,
    inventory_changer_vars::KnifeType,
    inventory_changer_vars::Wear,
    inventory_changer_vars::Seed,
    inventory_changer_vars::StatTrak,
    inventory_changer_vars::ApplyRequested,
    BombPlantAlertEnabled,
    grenade_prediction_vars::Enabled,
    grenade_prediction_vars::TrajectoryHue,
    grenade_prediction_vars::BounceHue,
    grenade_prediction_vars::BounceFriction
>;
